name: Build and Push Docker Image

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: manavmuthanna
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build -t manavmuthanna/text2sql:latest .

    - name: Push the Docker image
      run: |
        docker push yourusername/yourimagename:latest

    - name: Log out of Docker Hub
      run: |
        docker logout